language: ruby
bundler_args: --without development --deployment
cache: bundler
rvm:
  - 2.1.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - psql -c 'create database callem_test' -U postgres